import Link from "next/link";

export default function Home() {
  return <>
    <header className="shell nav"><div className="brand">MARGOTHEIA</div><nav className="navlinks"><a href="#oraculos">Oráculos</a><a href="#como-funciona">Como funciona</a><Link href="/auth/login">Entrar</Link><Link className="button" href="/consulta">Iniciar consulta</Link></nav></header>
    <main>
      <section className="shell hero"><div><div className="eyebrow">O oráculo que escuta antes de revelar</div><h1>Há perguntas que pedem um olhar mais profundo.</h1><p>Na Margotheia, Lunah acolhe sua questão antes das cartas e conduz uma leitura personalizada, unindo tradição oracular, simbolismo e inteligência artificial.</p><div className="actions"><Link className="button primary" href="/consulta">Iniciar minha consulta</Link><a className="button" href="#como-funciona">Conhecer a Margotheia</a></div><p className="hint">Sua primeira tiragem de 3 cartas não exige cadastro.</p></div><aside className="lunah"><div className="moon"/><h2>Lunah</h2><blockquote>“Antes das cartas, quero entender o que trouxe você até aqui.”</blockquote></aside></section>
      <section className="section" id="como-funciona"><div className="shell"><div className="eyebrow">Uma consulta começa na escuta</div><h2>Não entregamos três significados prontos.</h2><p className="lead">A pergunta, a posição de cada carta e as relações formadas na tiragem mudam a leitura. O Motor Oracular organiza esses sinais e Lunah transforma o conjunto em uma interpretação contextualizada.</p><div className="cards"><div className="card"><h3>1. Você conta</h3><p>Lunah compreende o que você busca e ajuda a dar foco à consulta.</p></div><div className="card"><h3>2. As cartas respondem</h3><p>O método é escolhido e as cartas formam uma estrutura única para aquela questão.</p></div><div className="card"><h3>3. Lunah interpreta</h3><p>A leitura integra posições, padrões, combinações e simbolismos em contexto.</p></div></div></div></section>
      <section className="section" id="oraculos"><div className="shell"><div className="eyebrow">Dois sistemas, duas linguagens</div><h2>Escolha seu oráculo — ou deixe Lunah orientar.</h2><div className="cards"><div className="card"><h3>Tarot de Marselha</h3><p>Arquétipos, desenvolvimento, conflitos internos, relações e caminhos.</p></div><div className="card"><h3>Petit Lenormand</h3><p>Leitura objetiva e combinatória para acontecimentos, movimentos e relações concretas.</p></div><div className="card"><h3>Recomendação de Lunah</h3><p>Conte sua situação e receba uma sugestão de oráculo e método adequada à pergunta.</p></div></div></div></section>
    </main>
    <footer><div className="shell"><div className="brand">MARGOTHEIA</div><p>Conteúdo destinado a maiores de 18 anos. Interpretações oraculares são simbólicas e reflexivas e não substituem orientação profissional especializada.</p></div></footer>
  </>;
}
